// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class ADM_Hotel
    {
        public ADM_Hotel()
        {
            Hospedagens = new HashSet<Hospedagens>();
        }

        public byte? CC_ADM { get; set; }
        [Key]
        public long CNPJ { get; set; }
        [StringLength(50)]
        public string Razao_Social { get; set; }
        [StringLength(50)]
        public string Nome_Fantasia { get; set; }
        public int? Inscr_Estad { get; set; }
        public short? Ramal_Principal { get; set; }
        [StringLength(50)]
        public string Email_Principal { get; set; }
        public byte DDD_Comercial1 { get; set; }
        public int Tel_Comercial1 { get; set; }
        public byte? DDD_Comercial2 { get; set; }
        public int? Tel_Comercial2 { get; set; }
        [Required]
        [StringLength(50)]
        public string Logradouro { get; set; }
        [Required]
        [StringLength(10)]
        public string Numero { get; set; }
        [StringLength(50)]
        public string Complemento { get; set; }
        [Required]
        [StringLength(30)]
        public string Bairro_Regiao { get; set; }
        [Required]
        [StringLength(50)]
        public string Cidade { get; set; }
        public int CEP { get; set; }
        [StringLength(30)]
        public string Estado_Provincia { get; set; }
        [Required]
        [StringLength(50)]
        public string Pais { get; set; }

        [InverseProperty("CNPJ_PrestadorNavigation")]
        public virtual ICollection<Hospedagens> Hospedagens { get; set; }
    }
}