// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Clientes
    {
        public Clientes()
        {
            Dados_Financeiros_Clientes = new HashSet<Dados_Financeiros_Clientes>();
            Hospedagens = new HashSet<Hospedagens>();
            Users_Clientes = new HashSet<Users_Clientes>();
        }

        [Key]
        public int Cod_Cliente { get; set; }
        [Required]
        [StringLength(100)]
        public string Nome_Completo { get; set; }
        [StringLength(64)]
        public string CPF { get; set; }
        [StringLength(64)]
        public string RG { get; set; }
        [StringLength(64)]
        public string Num_Passaporte { get; set; }
        [Column(TypeName = "date")]
        public DateTime Data_Nascimento { get; set; }
        [StringLength(15)]
        public string Genero { get; set; }
        public byte? DDI_Tel_Fixo { get; set; }
        public byte? DDD_Tel_Fixo { get; set; }
        [StringLength(64)]
        public string Num_Tel_Fixo { get; set; }
        public byte DDI_Tel_Celular { get; set; }
        public byte? DDD_Tel_Celular { get; set; }
        [StringLength(64)]
        public string Num_Tel_Celular { get; set; }
        public byte? DDI_Tel_Recado { get; set; }
        public byte? DDD_Tel_Recado { get; set; }
        [StringLength(64)]
        public string Num_Tel_Recado { get; set; }
        public byte? DDI_Tel_Comercial { get; set; }
        public byte? DDD_Tel_Comercial { get; set; }
        [StringLength(64)]
        public string Num_Tel_Comercial { get; set; }
        [StringLength(64)]
        public string Email_Principal { get; set; }
        [StringLength(64)]
        public string Email_Secundario { get; set; }
        [Required]
        [StringLength(50)]
        public string Logradouro { get; set; }
        [Required]
        [StringLength(10)]
        public string Numero { get; set; }
        [StringLength(50)]
        public string Complemento { get; set; }
        [Required]
        [StringLength(30)]
        public string Bairro_Regiao { get; set; }
        [Required]
        [StringLength(50)]
        public string Cidade { get; set; }
        [StringLength(20)]
        public string CEP_ZipCode { get; set; }
        [StringLength(30)]
        public string Estado_Provincia { get; set; }
        [Required]
        [StringLength(50)]
        public string Pais { get; set; }

        [InverseProperty("Cod_ClienteNavigation")]
        public virtual ICollection<Dados_Financeiros_Clientes> Dados_Financeiros_Clientes { get; set; }
        [InverseProperty("Cod_ClienteNavigation")]
        public virtual ICollection<Hospedagens> Hospedagens { get; set; }
        [InverseProperty("Cod_ClienteNavigation")]
        public virtual ICollection<Users_Clientes> Users_Clientes { get; set; }
    }
}