// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Compras
    {
        public Compras()
        {
            Contabilidade = new HashSet<Contabilidade>();
            Contas_Pagar = new HashSet<Contas_Pagar>();
        }

        public byte CC_Compras { get; set; }
        [Key]
        [StringLength(30)]
        public string Num_Pedido { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Emissao_Pedido { get; set; }
        public bool? Status_Pedido { get; set; }
        public long? Cod_Fornec { get; set; }
        [StringLength(50)]
        public string Fornecedor { get; set; }
        [StringLength(30)]
        public string Cod_Item { get; set; }
        [StringLength(50)]
        public string Descricao { get; set; }
        [StringLength(10)]
        public string Unid_Medida { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal? Qt_Itens { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal? Peso_Unidade { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal? Peso_Total { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Valor_Bruto { get; set; }
        [Column(TypeName = "decimal(3, 1)")]
        public decimal? Desconto { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Valor_Liquido { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Entrega { get; set; }
        [StringLength(3)]
        public string Tipo_Frete { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Frete { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Seguro { get; set; }
        [StringLength(30)]
        public string Cond_Pagamento { get; set; }
        public byte? Parcelas { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Valor_Parcela { get; set; }

        [ForeignKey(nameof(Cod_Fornec))]
        [InverseProperty(nameof(Fornecedores_Hotel.Compras))]
        public virtual Fornecedores_Hotel Cod_FornecNavigation { get; set; }
        [InverseProperty("Pedido_CompraNavigation")]
        public virtual ICollection<Contabilidade> Contabilidade { get; set; }
        [InverseProperty("Cod_PedidoCompraNavigation")]
        public virtual ICollection<Contas_Pagar> Contas_Pagar { get; set; }
    }
}