// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Contabilidade
    {
        [Key]
        public byte CC_Contabil { get; set; }
        public long? Cod_CC { get; set; }
        [StringLength(50)]
        public string Descr_CC { get; set; }
        [StringLength(30)]
        public string Pedido_Compra { get; set; }
        public int? Reserva_Hospedagem { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_OP { get; set; }
        [StringLength(15)]
        public string Tipo_Doc_OP { get; set; }
        public long? Doc_OP { get; set; }
        [StringLength(100)]
        public string Historico { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Debito { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Credito { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Saldo { get; set; }

        [ForeignKey(nameof(Pedido_Compra))]
        [InverseProperty(nameof(Compras.Contabilidade))]
        public virtual Compras Pedido_CompraNavigation { get; set; }
        [ForeignKey(nameof(Reserva_Hospedagem))]
        [InverseProperty(nameof(Hospedagens.Contabilidade))]
        public virtual Hospedagens Reserva_HospedagemNavigation { get; set; }
    }
}