// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Dados_Financeiros_Clientes
    {
        [Key]
        public int ID_Cartao { get; set; }
        public int? Cod_Cliente { get; set; }
        [StringLength(10)]
        public string Tipo1 { get; set; }
        [StringLength(30)]
        public string Banco_Adm1 { get; set; }
        [StringLength(20)]
        public string Bandeira1 { get; set; }
        [StringLength(64)]
        public string Num_Cartao1 { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Validade1 { get; set; }
        [StringLength(64)]
        public string CVV1 { get; set; }
        [StringLength(10)]
        public string Tipo2 { get; set; }
        [StringLength(30)]
        public string Banco_Adm2 { get; set; }
        [StringLength(20)]
        public string Bandeira2 { get; set; }
        [StringLength(64)]
        public string Num_Cartao2 { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Validade2 { get; set; }
        [StringLength(64)]
        public string CVV2 { get; set; }
        [StringLength(10)]
        public string Tipo3 { get; set; }
        [StringLength(30)]
        public string Banco_Adm3 { get; set; }
        [StringLength(20)]
        public string Bandeira3 { get; set; }
        [StringLength(64)]
        public string Num_Cartao3 { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Validade3 { get; set; }
        [StringLength(64)]
        public string CVV3 { get; set; }

        [ForeignKey(nameof(Cod_Cliente))]
        [InverseProperty(nameof(Clientes.Dados_Financeiros_Clientes))]
        public virtual Clientes Cod_ClienteNavigation { get; set; }
    }
}