// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class RH
    {
        public byte? Centro_Custo { get; set; }
        [Key]
        public int Matricula { get; set; }
        public int Cod_Funcionario { get; set; }
        public bool Sit_Cadastral { get; set; }
        public short? Ramal { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Cargo { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Ingresso { get; set; }
        [Column(TypeName = "date")]
        public DateTime Dt_Admissao { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Deslig_Afast { get; set; }

        [ForeignKey(nameof(Cod_Funcionario))]
        [InverseProperty(nameof(Funcionarios.RH))]
        public virtual Funcionarios Cod_FuncionarioNavigation { get; set; }
    }
}