// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Users_Clientes
    {
        [Key]
        public int ID_User { get; set; }
        [Required]
        [StringLength(12)]
        public string UserName { get; set; }
        [Required]
        [StringLength(100)]
        public string Email_Login { get; set; }
        [Required]
        [StringLength(64)]
        public string Senha { get; set; }
        public int? Cod_Cliente { get; set; }

        [ForeignKey(nameof(Cod_Cliente))]
        [InverseProperty(nameof(Clientes.Users_Clientes))]
        public virtual Clientes Cod_ClienteNavigation { get; set; }
    }
}