// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Users_Funcionarios
    {
        [Key]
        public int ID_User { get; set; }
        [Required]
        [StringLength(12)]
        public string UserName { get; set; }
        [Required]
        [StringLength(64)]
        public string Senha { get; set; }
        [Required]
        [StringLength(10)]
        public string Matricula { get; set; }
        public int? Cod_Funcionario { get; set; }

        [ForeignKey(nameof(Cod_Funcionario))]
        [InverseProperty(nameof(Funcionarios.Users_Funcionarios))]
        public virtual Funcionarios Cod_FuncionarioNavigation { get; set; }
    }
}