// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Acomodacoes
    {
        public Acomodacoes()
        {
            Hospedagens = new HashSet<Hospedagens>();
        }

        [Key]
        public int ID_Acomod { get; set; }
        [Required]
        [StringLength(15)]
        public string Tipo_Acomodacao { get; set; }
        [StringLength(10)]
        public string Nivel { get; set; }
        [StringLength(10)]
        public string Categoria { get; set; }
        [Required]
        [StringLength(5)]
        public string Num_Ap { get; set; }
        public byte Tam_Ap { get; set; }
        public bool? Telefone { get; set; }
        public bool? TV { get; set; }
        public bool? TV_Serv_Assin { get; set; }
        public bool? Area_Lazer { get; set; }
        public bool? Frigobar { get; set; }
        public bool? Hidromassagem { get; set; }

        [InverseProperty("Num_ApNavigation")]
        public virtual ICollection<Hospedagens> Hospedagens { get; set; }
    }
}