// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Contas_Receber
    {
        public byte? CC_Contas_Receber { get; set; }
        [Key]
        public int Ordem_Recebimento { get; set; }
        public int? ID_Reserva { get; set; }
        [StringLength(50)]
        public string Natureza_Cred { get; set; }
        [StringLength(1000)]
        public string Descricao_Cred { get; set; }
        [StringLength(500)]
        public string Observacao_Cred { get; set; }
        [StringLength(30)]
        public string Tipo_Doc { get; set; }
        public long? Num_Doc { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Vencto { get; set; }
        public int? Cod_Pagador { get; set; }
        [StringLength(100)]
        public string Nome_Razao_Social { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Valor_Bruto { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Tributos { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Valor_Liquido { get; set; }
        public long? Despesa { get; set; }
        public byte? Cod_Compens { get; set; }
        [StringLength(50)]
        public string Banco { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Liquidacao { get; set; }

        [ForeignKey(nameof(ID_Reserva))]
        [InverseProperty(nameof(Hospedagens.Contas_Receber))]
        public virtual Hospedagens ID_ReservaNavigation { get; set; }
    }
}