// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Contas_Pagar
    {
        public byte? CC_Contas_Pagar { get; set; }
        [Key]
        public int Ordem_Pgto { get; set; }
        [StringLength(30)]
        public string Cod_PedidoCompra { get; set; }
        [StringLength(50)]
        public string Natureza_Pgto { get; set; }
        [StringLength(1000)]
        public string Descricao_Pgto { get; set; }
        [StringLength(500)]
        public string Observacao_Pgto { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Vencto { get; set; }
        public int? Cod_Benef { get; set; }
        [StringLength(50)]
        public string Razao_Social { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Valor_Bruto { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Tributos { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal? Valor_Liquido { get; set; }
        public long? Despesa { get; set; }
        [StringLength(30)]
        public string Tipo_Pgto { get; set; }
        public byte? Cod_Compens { get; set; }
        [StringLength(50)]
        public string Banco { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dt_Liquidacao { get; set; }

        [ForeignKey(nameof(Cod_PedidoCompra))]
        [InverseProperty(nameof(Compras.Contas_Pagar))]
        public virtual Compras Cod_PedidoCompraNavigation { get; set; }
    }
}