// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace UniHotel___BackEnd
{
    public partial class Funcionarios
    {
        public Funcionarios()
        {
            Hospedagens = new HashSet<Hospedagens>();
            RH = new HashSet<RH>();
            Users_Funcionarios = new HashSet<Users_Funcionarios>();
        }

        [Key]
        public int Cod_Funcionario { get; set; }
        [Required]
        [StringLength(100)]
        public string Nome_Completo { get; set; }
        [Column(TypeName = "date")]
        public DateTime Data_Nasc { get; set; }
        [StringLength(15)]
        public string Genero { get; set; }
        [StringLength(10)]
        public string Estado_Civil { get; set; }
        [Required]
        [StringLength(15)]
        public string Tipo_Contrato { get; set; }
        [Required]
        [StringLength(40)]
        public string Cargo { get; set; }
        [Required]
        [StringLength(30)]
        public string Nivel { get; set; }
        public byte? DDI_Tel_Fixo { get; set; }
        public byte? DDD_Tel_Fixo { get; set; }
        [StringLength(64)]
        public string Num_Tel_Fixo { get; set; }
        public byte DDI_Tel_Celular { get; set; }
        public byte? DDD_Tel_Celular { get; set; }
        [StringLength(64)]
        public string Num_Tel_Celular { get; set; }
        public byte? DDI_Tel_Recado { get; set; }
        public byte? DDD_Tel_Recado { get; set; }
        [StringLength(64)]
        public string Num_Tel_Recado { get; set; }
        [StringLength(64)]
        public string Email_Principal { get; set; }
        [StringLength(64)]
        public string Email_Secundario { get; set; }
        [StringLength(64)]
        public string Email_Corporativo { get; set; }
        [Required]
        [StringLength(50)]
        public string Logradouro { get; set; }
        [Required]
        [StringLength(10)]
        public string Numero { get; set; }
        [StringLength(50)]
        public string Complemento { get; set; }
        [Required]
        [StringLength(30)]
        public string Bairro_Regiao { get; set; }
        [Required]
        [StringLength(50)]
        public string Cidade { get; set; }
        [Required]
        [StringLength(20)]
        public string Cep_ZipCode { get; set; }
        [StringLength(30)]
        public string Estado_Provincia { get; set; }
        [Required]
        [StringLength(50)]
        public string Pais { get; set; }
        [StringLength(64)]
        public string CPF { get; set; }
        [StringLength(64)]
        public string RG { get; set; }
        [StringLength(2)]
        public string UF_RG { get; set; }
        [StringLength(64)]
        public string RNE { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Val_RNE { get; set; }
        [StringLength(64)]
        public string Num_Passaporte { get; set; }
        [StringLength(64)]
        public string Num_CTPS { get; set; }
        [StringLength(2)]
        public string UF_CTPS { get; set; }
        [StringLength(64)]
        public string PIS { get; set; }
        [StringLength(64)]
        public string Num_Titulo_Eleitor { get; set; }
        [StringLength(2)]
        public string UF_Titulo_Eleitor { get; set; }
        [StringLength(64)]
        public string Num_Reservista { get; set; }
        [StringLength(64)]
        public string RegistCivil_Mat { get; set; }
        [StringLength(2)]
        public string RegistCivil_UF { get; set; }
        [StringLength(30)]
        public string Nivel_Formacao { get; set; }
        [StringLength(10)]
        public string Situac_Formacao { get; set; }
        [StringLength(50)]
        public string Curso { get; set; }
        [StringLength(100)]
        public string Instituicao { get; set; }

        [InverseProperty("Mat_Func_ReservaNavigation")]
        public virtual ICollection<Hospedagens> Hospedagens { get; set; }
        [InverseProperty("Cod_FuncionarioNavigation")]
        public virtual ICollection<RH> RH { get; set; }
        [InverseProperty("Cod_FuncionarioNavigation")]
        public virtual ICollection<Users_Funcionarios> Users_Funcionarios { get; set; }
    }
}